#!/bin/bash

install-visualvm() {

    echo
    echo "Installing VisualVM"

    sdk install visualvm 2.0.2 >> logs/bigbang.log 2>> /dev/null

}

install-eclipse() {

    echo
    echo "Installing Eclipse"

    wget http://mirror.nbtelecom.com.br/eclipse/technology/epp/downloads/release/2020-03/R/eclipse-jee-2020-03-R-incubation-linux-gtk-x86_64.tar.gz >> logs/bigbang.log 2>> /dev/null

    sudo tar -xvzf eclipse-jee-2020-03-R-incubation-linux-gtk-x86_64.tar.gz --directory /opt/work/ides >> logs/bigbang.log 2>> /dev/null

    echo "$(echo -e -n '-vm\n/home/'$USERNAME'/.sdkman/candidates/java/current/bin/java\n'; cat /opt/work/ides/eclipse/eclipse.ini)" > eclipse.ini
    
    sudo mv eclipse.ini /opt/work/ides/eclipse/eclipse.ini

    sudo desktop-file-install support/eclipse.desktop >> logs/bigbang.log 2>> /dev/null

    rm -rf eclipse-jee-2020-03-R-incubation-linux-gtk-x86_64.tar.gz >> logs/bigbang.log 2>> /dev/null
}


install-intellij() {

    echo
    echo "Installing Intellij Community"

    wget https://download-cf.jetbrains.com/idea/ideaIC-2020.1.1.tar.gz >> logs/bigbang.log 2>> /dev/null

    sudo tar -xvzf ideaIC-2020.1.1.tar.gz --directory /opt/work/ides >> logs/bigbang.log 2>> /dev/null

    sudo desktop-file-install support/intellij.desktop >> logs/bigbang.log 2>> /dev/null

    rm -rf ideaIC-2020.1.1.tar.gz
}

install-visual-studio-code() {

    echo
    echo "Installing Visual Studio Code"

    wget https://az764295.vo.msecnd.net/stable/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/code_1.45.1-1589445302_amd64.deb >> logs/bigbang.log 2>> /dev/null

    sudo dpkg -i code_1.45.1-1589445302_amd64.deb >> logs/bigbang.log 2>> /dev/null

    rm -rf code_1.45.1-1589445302_amd64.deb
}

install-google-chrome() {

    echo
    echo "Installing Google Chrome"

    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb >> logs/bigbang.log 2>> /dev/null

    sudo dpkg -i google-chrome-stable_current_amd64.deb >> logs/bigbang.log 2>> /dev/null

    rm -rf google-chrome-stable_current_amd64.deb
}

install-postman() {

    echo
    echo "Installing Postman"

    sudo snap install postman >> logs/bigbang.log 2>> /dev/null
}

if ! [ -x "$(command -v visualvm)" ]; then
    install-visualvm
    echo "VisualVM was successfully installed!"
else
    echo "VisualVM is already installed!"
fi

if ! [ -x "$(command -v /opt/work/ides/eclipse/eclipse)" ]; then
    install-eclipse
    echo "Eclipse was successfully installed!"
else
    echo "Eclipse is already installed!"
fi

if ! [ -x "$(command -v /opt/work/ides/idea-IC-201.7223.91/bin/idea.sh)" ]; then
    install-intellij
    echo "Intellij Community was successfully installed!"
else
    echo "Intellij Community is already installed!"
fi

if ! [ -x "$(command -v code)" ]; then
    install-visual-studio-code
    echo "Visual Studio Code was successfully installed!"
else
    echo "Visual Studio Code is already installed!"
fi

if ! [ -x "$(command -v google-chrome)" ]; then
    install-google-chrome
    echo "Google Chrome was successfully installed!"
else
    echo "Google Chrome is already installed!"
fi

if ! [ -x "$(command -v postman)" ]; then
    install-postman
    echo "Postman Code was successfully installed!"
else
    echo "Postman is already installed!"
fi

