#!/bin/bash

install-docker() {

    echo
    echo "Installing Docker"

    sudo apt-get install -y apt-transport-https ca-certificates gnupg-agent software-properties-common >> logs/bigbang.log 2>> /dev/null

    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - >> logs/bigbang.log 2>> /dev/null

    sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable" >> logs/bigbang.log 2>> /dev/null

   sudo apt-get update -y >> logs/bigbang.log 2>> /dev/null

   sudo apt-get install -y docker-ce docker-ce-cli containerd.io >> logs/bigbang.log 2>> /dev/null
   
   sudo usermod -aG docker ${USER} >> logs/bigbang.log 2>> /dev/null

}

install-docker