#!/bin/bash

echo -e "################################################"
echo -e "       BIGBANG JAVA DEVELOPER MACHINE           "
echo -e "################################################"

echo "First, enter your user password:"
read -s password

update-ubuntu() {

    echo
    echo "Updating Ubuntu"

    mkdir -p logs

    echo $password | sudo -S apt update -y >> logs/bigbang.log 2>> /dev/null
}

create-base-folders() {

    echo
    echo "Checking Base Folders"

    sudo mkdir -p /opt/work
    sudo chown -R $USERNAME:$USERNAME /opt/work
    sudo mkdir -p /opt/work/ides
    sudo mkdir -p /opt/work/projects
    sudo mkdir -p /opt/work/workspaces
}

install-base() {

    echo
    echo "Checking Base Packages"

    if ! [ -x "$(command -v htop)" ]; then
        echo "Installing htop"
        sudo apt install -y htop >> logs/bigbang.log 2>> /dev/null
        echo "htop was successfully installed!"
    else
        echo "htop is already installed!"
    fi

    if ! [ -x "$(command -v httpie)" ]; then
        echo "Installing httpie"
        sudo apt install -y httpie >> logs/bigbang.log 2>> /dev/null
        echo "httpie was successfully installed!"
    else
        echo "httpie is already installed!"
    fi

    if ! [ -x "$(command -v jq)" ]; then
        echo "Installing jq"
        sudo apt install -y jq >> logs/bigbang.log 2>> /dev/null
        echo "jq was successfully installed!"
    else
        echo "jq is already installed!"
    fi

    if ! [ -x "$(command -v curl)" ]; then
        echo "Installing curl"
        sudo apt install -y curl >> logs/bigbang.log 2>> /dev/null
        echo "curl was successfully installed!"
    else
        echo "curl is already installed!"
    fi

    if ! [ -x "$(command -v vim)" ]; then
        echo "Installing vim"
        sudo apt install -y vim >> logs/bigbang.log 2>> /dev/null
        echo "vim was successfully installed!"
    else
        echo "vim is already installed!"
    fi

    if ! [ -x "$(command -v meld)" ]; then
        echo "Installing meld"
        sudo apt install -y meld >> logs/bigbang.log 2>> /dev/null
        echo "meld was successfully installed!"
    else
        echo "meld is already installed!"
    fi

    if ! [ -x "$(command -v libxml2-utils)" ]; then
        echo "Installing libxml2-utils"
        sudo apt install -y libxml2-utils >> logs/bigbang.log 2>> /dev/null        
        echo "libxml2-utils was successfully installed!"
    else
        echo "libxml2-utils is already installed!"
    fi 
    
}

echo 
echo "BIG BANG MY MACHINE"

update-ubuntu

if  [[ $1 != "--only-gui" ]]; then

    create-base-folders

    install-base 

    source boom-server-tools

    source boom-developer-tools

fi

if [ ! -z "$1" ]; then
    if  [ $1 == "--with-gui" ] || [ $1 == "--only-gui" ]; then
        source boom-gui-tools
    fi
fi



